### ISSUE TITLE
broken/unavailable links

### ISSUE THREAD

**Issue by Akurosia** [karashiiro/xiv-resources#10]
unavailable:
https://horus-hunts.net
https://textools.dualwield.net

deprecated:
`https://github.com/ufx/SaintCoinach` is deprecated, maybe link `https://github.com/xivapi/SaintCoinach`
`https://github.com/kalilistic/ACT.Kapture` ( no ACT plugin as alternative, but has a dalamud plugin now `https://github.com/kalilistic/Dalamud.Kapture`)

others:
`https://github.com/LeonBlade/BurningDownTheHouse` moved to `https://github.com/LeonBlade/BDTHPlugin`

**Comment by karashiiro** [comment]
Updated, thanks!
